# This file exists so users can easily get started with the Circuit
# Knitting Toolbox in a container using Docker Compose.
#
# Instructions are available at:
# https://qiskit-extensions.github.io/circuit-knitting-toolbox/install.html#option-3-use-within-docker

services:
  notebook:
    build: .
    platform: linux/amd64
    restart: unless-stopped
    # The following line allows Ray to use /dev/shm rather than warn
    # about using /tmp
    shm_size: "10.08gb"
    ports:
      - 8888:8888
    volumes:
      - circuit-knitting-toolbox:/home/jovyan/persistent-volume

volumes:
  circuit-knitting-toolbox:
