version: "3.4"

services:
  notebook:
    build: .
    platform: linux/amd64
    restart: unless-stopped
    # The following line allows Ray to use /dev/shm rather than warn
    # about using /tmp
    shm_size: "10.08gb"
    ports:
      - 8888:8888
    volumes:
      - circuit-knitting-toolbox:/home/jovyan/persistent-volume

volumes:
  circuit-knitting-toolbox:
